const PRODUCTS = [
  {
    id: 1,
    name: "Fresh Bananas (1 kg)",
    price: 49,
    mrp: 60,
    category: "Fruits & Vegetables",
    icon: "🍌",
    delivery: "Delivered in 12 mins",
    image: "https://source.unsplash.com/400x300/?banana",
  },
  {
    id: 2,
    name: "Full Cream Milk (1 L)",
    price: 64,
    mrp: 70,
    category: "Dairy & Eggs",
    icon: "🥛",
    delivery: "Delivered in 10 mins",
    image: "https://source.unsplash.com/400x300/?milk",
  },
  {
    id: 3,
    name: "Parle-G Biscuits (800 g)",
    price: 72,
    mrp: 80,
    category: "Snacks & Biscuits",
    icon: "🍪",
    delivery: "Delivered in 15 mins",
    image: "https://source.unsplash.com/400x300/?biscuits",
  },
  {
    id: 4,
    name: "Basmati Rice (5 kg)",
    price: 449,
    mrp: 520,
    category: "Grocery & Staples",
    icon: "🍚",
    delivery: "Delivered in 18 mins",
    image: "https://source.unsplash.com/400x300/?rice",
  },
  {
    id: 5,
    name: "Tomatoes (1 kg)",
    price: 35,
    mrp: 45,
    category: "Fruits & Vegetables",
    icon: "🍅",
    delivery: "Delivered in 11 mins",
    image: "https://source.unsplash.com/400x300/?tomato",
  },
  {
    id: 6,
    name: "Cold Drink (1.25 L)",
    price: 85,
    mrp: 100,
    category: "Cold Drinks & Juices",
    icon: "🥤",
    delivery: "Delivered in 16 mins",
    image: "https://source.unsplash.com/400x300/?softdrink",
  },
  {
    id: 7,
    name: "Brown Bread (400 g)",
    price: 42,
    mrp: 50,
    category: "Bakery",
    icon: "🍞",
    delivery: "Delivered in 14 mins",
    image: "https://source.unsplash.com/400x300/?bread",
  },
  {
    id: 8,
    name: "Potato Chips (Family Pack)",
    price: 95,
    mrp: 120,
    category: "Snacks & Biscuits",
    icon: "🍟",
    delivery: "Delivered in 13 mins",
    image: "https://source.unsplash.com/400x300/?chips",
  },
  {
    id: 9,
    name: "Yogurt Cup (6 x 100g)",
    price: 120,
    mrp: 150,
    category: "Dairy & Eggs",
    icon: "🧀",
    delivery: "Delivered in 17 mins",
    image: "https://source.unsplash.com/400x300/?yogurt",
  },
  {
    id: 10,
    name: "Premium Atta (10 kg)",
    price: 399,
    mrp: 450,
    category: "Grocery & Staples",
    icon: "🥙",
    delivery: "Delivered in 20 mins",
    image: "https://source.unsplash.com/400x300/?wheatflour",
  },
];
